services:
  postgres:
    image: postgres
    restart: always
    ports: 
      - "9090:5432"
    environment:
      - DATABASE_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "grstiven1004@gmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "24681012Ss"
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - postgres